target 'storemed' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Platform Mobile

pod 'Alamofire', '~> 4.8.0'
pod 'Typist'
pod 'PKHUD', '~> 5.0'
pod 'SDWebImage'
pod 'EasyDi'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftyBeaver', '~> 1.7.0'

target 'storemedTests' do
inherit! :search_paths
# Pods for testing
end

end
